name: Slow Food Dublin
favicon: null
layout_spectrum: 0.568762059090659
typography_spectrum: 0.7136460761539638
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.055123383877798915
  lightness: 0.9152208522427827
  saturation: 0.19573330599814653
  rhythmicContrast: 0.16429823846556246
purpose: []
